services:
  redis-auth:
    image: redis:7-alpine
    command: >
      sh -c "
      echo '
        user myuser on allkeys allchannels allcommands >mypassword
        user default on allkeys allchannels allcommands >password
      ' > /tmp/users.acl &&
      redis-server --aclfile /tmp/users.acl"
    networks:
      - default

  redis:
    image: redis:7-alpine
    networks:
      - default

  redis-auth-node-1: &redis-template
    image: redis:7-alpine
    command: >
      redis-server 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --port 6379 
      --bind 0.0.0.0 
      --protected-mode no
      --requirepass "password"
    networks:
      - default

  redis-auth-node-2: *redis-template
  redis-auth-node-3: *redis-template

  redis-node-1: &redis-template
    image: redis:7-alpine
    command: >
      redis-server 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --port 6379 
      --bind 0.0.0.0 
      --protected-mode no
    networks:
      - default

  redis-node-2: *redis-template
  redis-node-3: *redis-template

  memcached:
    image: memcached:alpine
    networks:
      - default

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - redis-auth
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-auth-node-1
      - redis-auth-node-2
      - redis-auth-node-3
      - memcached
      - mysql
    stdin_open: true
    networks:
      - default

networks:
  default:
    name: symfony-circuit-breaker-tests
    attachable: true
