name: Tests

on:
  push:

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compose
        run: docker compose up -d

      - name: Create redis cluster with auth
        run: |
          docker run --rm \
            --network symfony-circuit-breaker-tests \
            redis:alpine \
            redis-cli \
            -a password \
            --cluster create \
            redis-auth-node-1:6379 \
            redis-auth-node-2:6379 \
            redis-auth-node-3:6379 \
            --cluster-replicas 0 \
            --cluster-yes

      - name: Create redis cluster no auth
        run: |
          docker run --rm \
            --network symfony-circuit-breaker-tests \
            redis:alpine \
            redis-cli \
            --cluster create \
            redis-node-1:6379 \
            redis-node-2:6379 \
            redis-node-3:6379 \
            --cluster-replicas 0 \
            --cluster-yes

      - name: Composer install
        run: composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

      - name: PHPStan
        run: docker compose exec -t php vendor/bin/phpstan analyse src tests --memory-limit=256M

      - name: PHPcs
        run: docker compose exec -t php vendor/bin/phpcs src tests

      - name: Run phpunit
        run: docker compose exec -t php vendor/bin/phpunit
